baseurl = "http://blog.guthnur.net/"
languageCode = "en-us"
title = "Moos3"
paginate = 5
DisqusShortname = "moos3"
Copyright = "All rights reserved - 2015"
canonifyurls = true
pygmentsStyle = "monokai"

[params]
  description = "Knowledge is power but Openly Shared knowledge is real power!"
  cover = "images/bg2.jpg"
  author = "Richard Genthner"
  authorlocation = "Maine, USA"
  authorwebsite = "http://guthnur.net"
  bio = "System Engineer, Open source enthusiast."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-25578688-2"
  githubName = "moos3"
  twitterName = "moos3"
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  indentifier = "blog"
  url = "/"

[[menu.main]]
  name = "About Me"
  weight = -120
  indentifier = "about"
  url = "/about"

[[menu.main]]
  name = "Github repos"
  weight = 100
  pre = "<h3>Follow me</h3>"
  url = "https://github.com/moos3"

[[menu.main]]
  name = "Twitter timeline"
  weight = 101
  url = "https://twitter.com/moos3"
